package com.jellyfish.jfgnbody.gui;

import com.jellyfish.jfgnbody.interfaces.Writable;
import com.jellyfish.jfgnbody.starter.Main;
import javax.swing.JSpinner.DefaultEditor;

/**
 *
 * @author thw
 */
public class NewSimulationDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewSimulationDialog.
     *
     * @param parent
     */
    public NewSimulationDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        ((DefaultEditor) this.nbodyCountSpinner.getEditor()).getTextField().setEditable(false);
        ((DefaultEditor) this.iSpeedSpinner.getEditor()).getTextField().setEditable(false);
        ((DefaultEditor) this.massiveBodyCountSpinner.getEditor()).getTextField().setEditable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nbodyCountLabel = new javax.swing.JLabel();
        iterationSpeddLabel = new javax.swing.JLabel();
        newSimulationSubtitleLabel = new javax.swing.JLabel();
        newSimulationStartButton = new javax.swing.JButton();
        newSimulationCancelButton = new javax.swing.JButton();
        nbodyCountSpinner = new javax.swing.JSpinner();
        iSpeedSpinner = new javax.swing.JSpinner();
        massiveBodyCountSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New NBody simulation");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setResizable(false);

        nbodyCountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nbodyCountLabel.setText("Enter a body amount >= 100 & <= 1 410 065 408 : ");

        iterationSpeddLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        iterationSpeddLabel.setText("Iteration speed in milliseconds >= 10 & <= 1000 : ");

        newSimulationSubtitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newSimulationSubtitleLabel.setText("Please submit a body amout (N = solor mass count) and iteration\\nspeed for a new simulation.");

        newSimulationStartButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newSimulationStartButton.setText("Start simulation");
        newSimulationStartButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        newSimulationStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSimulationStartButtonActionPerformed(evt);
            }
        });

        newSimulationCancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newSimulationCancelButton.setText("Cancel");
        newSimulationCancelButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        newSimulationCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSimulationCancelButtonActionPerformed(evt);
            }
        });

        nbodyCountSpinner.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nbodyCountSpinner.setModel(new javax.swing.SpinnerNumberModel(1000, 100, 1410065408, 1000));
        nbodyCountSpinner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        nbodyCountSpinner.setDoubleBuffered(true);

        iSpeedSpinner.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        iSpeedSpinner.setModel(new javax.swing.SpinnerNumberModel(100, 10, 1000, 10));
        iSpeedSpinner.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        iSpeedSpinner.setDoubleBuffered(true);

        massiveBodyCountSpinner.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        massiveBodyCountSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1, 1));
        massiveBodyCountSpinner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        massiveBodyCountSpinner.setDoubleBuffered(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Extra massiv bodies added to simulation :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newSimulationSubtitleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(newSimulationCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newSimulationStartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nbodyCountLabel)
                                    .addComponent(iterationSpeddLabel))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nbodyCountSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(iSpeedSpinner)
                            .addComponent(massiveBodyCountSpinner))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(newSimulationSubtitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbodyCountLabel)
                    .addComponent(nbodyCountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iterationSpeddLabel)
                    .addComponent(iSpeedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(massiveBodyCountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSimulationStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSimulationCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newSimulationCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSimulationCancelButtonActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_newSimulationCancelButtonActionPerformed

    @SuppressWarnings("UnnecessaryBoxing")
    private void newSimulationStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSimulationStartButtonActionPerformed
        Main.start((MainFrame) this.getParent(), (int) this.nbodyCountSpinner.getValue(),
                (int) this.iSpeedSpinner.getValue(), 
                new Integer((int) this.massiveBodyCountSpinner.getValue()));
        this.setVisible(false);
        final Writable w = ((MainFrame) this.getParent()).getnBodyPanel().getWriter();
        if (w != null) w.writeln(
                String.format("--------------------------------------------------------\n" + 
                    "-    New simulation :\n-    Body count = %d\n-    Iteration speed = %d\n" +
                    "--------------------------------------------------------", 
                (int) this.nbodyCountSpinner.getValue(), (int) this.iSpeedSpinner.getValue()));
        this.dispose();
    }//GEN-LAST:event_newSimulationStartButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner iSpeedSpinner;
    private javax.swing.JLabel iterationSpeddLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner massiveBodyCountSpinner;
    private javax.swing.JLabel nbodyCountLabel;
    private javax.swing.JSpinner nbodyCountSpinner;
    private javax.swing.JButton newSimulationCancelButton;
    private javax.swing.JButton newSimulationStartButton;
    private javax.swing.JLabel newSimulationSubtitleLabel;
    // End of variables declaration//GEN-END:variables

}
